### ISSUE TITLE
 Error: Can't find end of central directory : is this a zip file ?

### ISSUE THREAD

**Issue by peassuncao** [open-xml-templating/pizzip#22]
Hi i created a simple docx with:

{#Beers}
{Brand} – {Price}
{/Beers}

When i run (Pizzip 3.1.1):
var data = new PizZip("C:/..(some path)../Beers2.docx") i get:

(node:10108) UnhandledPromiseRejectionWarning: Error: Can't find end of central directory : is this a zip file ?
    at ZipEntries.readEndOfCentral (C:\GitHub\vue\docxCreator\node_modules\pizzip\js\zipEntries.js:191:15)
    at ZipEntries.load (C:\GitHub\vue\docxCreator\node_modules\pizzip\js\zipEntries.js:296:10)
    at new ZipEntries (C:\GitHub\vue\docxCreator\node_modules\pizzip\js\zipEntries.js:32:10)
    at PizZip.module.exports [as load] (C:\GitHub\vue\docxCreator\node_modules\pizzip\js\load.js:25:20)
    at fazer (C:\GitHub\vue\docxCreator\mydocxtemplater.js:42:16)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by edi9999** [comment]
It should be instead : 

```
var data = new PizZip(fs.readFIleSync("C:/..(some path)../Beers2.docx", "binary")) 
```

**Comment by daschi** [comment]
I'm also seeing this issue and I don't think `fs.readFileSync` is compatible iwth the browser. Is there another method to use ? I'm using `PizZipUtils.getBinaryContent(url, callback);` from the docxtemplater demo

**Comment by edi9999** [comment]
Hello @daschi , 

yes, in the browser you can run the following :

```html
<html>
    <body>
        <button onclick="generate()">Generate document</button>
    </body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/docxtemplater/3.31.2/docxtemplater.js"></script>
    <script src="https://unpkg.com/pizzip@3.1.1/dist/pizzip.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/1.3.8/FileSaver.js"></script>
    <script src="https://unpkg.com/pizzip@3.1.1/dist/pizzip-utils.js"></script>
    <!--
    Mandatory in IE 6, 7, 8 and 9.
    -->
    <!--[if IE]>
        <script
            type="text/javascript"
            src="https://unpkg.com/pizzip@3.1.1/dist/pizzip-utils-ie.js"
        ></script>
    <![endif]-->
    <script>
        function loadFile(url, callback) {
            PizZipUtils.getBinaryContent(url, callback);
        }
        window.generate = function generate() {
            loadFile(
                "https://docxtemplater.com/tag-example.docx",
                function (error, content) {
                    if (error) {
                        throw error;
                    }
                    var zip = new PizZip(content);
                    var doc = new window.docxtemplater(zip, {
                        paragraphLoop: true,
                        linebreaks: true,
                    });

                    // Render the document (Replace {first_name} by John, {last_name} by Doe, ...)
                    doc.render({
                        first_name: "John",
                        last_name: "Doe",
                        phone: "0652455478",
                        description: "New Website",
                    });

                    var out = doc.getZip().generate({
                        type: "blob",
                        mimeType:
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                        // compression: DEFLATE adds a compression step.
                        // For a 50MB output document, expect 500ms additional CPU time
                        compression: "DEFLATE",
                    });
                    // Output the document using Data-URI
                    saveAs(out, "output.docx");
                }
            );
        };
    </script>
</html>
```

Most likely, your request to the server is not complete (see the devtools of your browser to see what is happening).
